pipeline:
  build:
    image: docker:latest
    secrets: [ dockerhub_user, dockerhub_pwd ]
    commands:
      - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PWD
      - docker build --pull -t tokend/web-client:${DRONE_COMMIT_SHA} .
      - docker push tokend/web-client:${DRONE_COMMIT_SHA}
    environment:
      - DOCKERHUB_USER=$$DOCKERHUB_USER
      - DOCKERHUB_PWD=$$DOCKERHUB_PWD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push
  dh_publish:
    image: docker:latest
    secrets: [ dockerhub_user, dockerhub_pwd ]
    commands:
      - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PWD
      - docker pull tokend/web-client:${DRONE_COMMIT_SHA}
      - docker tag tokend/web-client:${DRONE_COMMIT_SHA} tokend/web-client:latest
      - docker push tokend/web-client:latest
    environment:
      - DOCKERHUB_USER=$$DOCKERHUB_USER
      - DOCKERHUB_PWD=$$DOCKERHUB_PWD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: master
      event: push
